src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $illustration = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column]
    private ?float $tva = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    private ?Category $category = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getIllustration(): ?string
    {
        return $this->illustration;
    }

    public function setIllustration(string $illustration): static
    {
        $this->illustration = $illustration;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): static
    {
        $this->price = $price;

        return $this;
    }

	public function getPriceWT()
	{
		return $this->price * (1 + $this->tva / 100);
	}

    public function getTva(): ?float
    {
        return $this->tva;
    }

    public function setTva(float $tva): static
    {
        $this->tva = $tva;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Class\Cart;
use App\Repository\ProductRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class CartController extends AbstractController
{
    #[Route('/panier', name: 'app_cart')]
    public function index(Cart $cart): Response
    {
        return $this->render('cart/index.html.twig', [
			'cart' => $cart->getCart(),
			'totalWT' => $cart->getTotalWT()
		]);
    }

	#[Route('/cart/add/{id}', name: 'app_cart_add')]
	public function add($id, Cart $cart, ProductRepository $productRepository, Request $request): Response
	{
		$product = $productRepository->findOneById($id);

		$cart->add($product);

		$this->addFlash(
			'success',
			'Votre produit a bien été ajouté au panier');

		return $this->redirect($request->headers->get('referer'));
	}

	#[Route('/cart/decrease/{id}', name: 'app_cart_decrease')]
	public function decrease($id, Cart $cart): Response
	{
		$cart->decrease($id);

		$this->addFlash(
			'success',
			'Votre produit a bien été supprimé du panier');

		return $this->redirectToRoute('app_cart');
	}

	#[Route('/cart/remove', name: 'app_cart_remove')]
	public function remove(Cart $cart): Response
	{
		$cart->remove();

		return $this->redirectToRoute('app_home');
	}

}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="container my-5">
        <h1>Mon panier</h1>

        <div class="row">

            <div class="col-md-8">

                {% for product in cart %}
                    <div class="row mt-2">
                        <div class="col-md-2">
                            <img src="/uploads/{{ product.object.illustration }}" class="img-fluid" alt="{{ product.object.name }}">
                        </div>
                        <div class="col-md-6">
                            <strong>{{ product.object.name }}</strong>
                            <span class="d-block small">Prix unitaire : {{ product.object.priceWT|price }}</span>
                        </div>
                        <div class="col-md-2 text-right">

                            <a href="{{ path('app_cart_decrease', {id : product.object.id} ) }}">-</a> <span class="badge text-bg-secondary">x{{ product.quantity }}</span> <a href="{{ path('app_cart_add', {id : product.object.id} ) }}">+</a>
                        </div>
                        <div class="col-md-2">
                            <strong>{{ (product.quantity * product.object.priceWT)|price }}</strong>
                        </div>
                    </div>
                {% endfor %}
                <a href="{{ path('app_cart_remove') }}" class="small d-block mt-3">Vider le panier</a>
            </div>

            <div class="col-md-4">
                <div class="bg-light p-3 rounded-2">
                    <div class="d-flex justify-content-between">
                        <span class="fw-bold">Total produit</span>
                        <span>{{ fullCartQuantity }}</span>
                    </div>

                    <div class="d-flex justify-content-between mt-3">
                        <span class="fw-bold">Prix total TTC</span>
                        <span>{{ totalWT|price }}</span>
                    </div>

                    <a href="" class="btn btn-primary mt-3 w-100">Commander</a>
                </div>
            </div>

        </div>

    </div>

{% endblock %}